openapi: 3.0.0
info:
    title: Jobs API
    contact: {}
    version: "1.0"
servers:
    - url: https://jobs-api-docs-4s4o.onrender.com/api/v1
      variables: {}
paths:
    /auth/register:
        post:
            tags:
                - Auth
            summary: Register User
            operationId: RegisterUser
            parameters: []
            requestBody:
                description: ""
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/RegisterUserRequest"
                                - example:
                                      name: Jane Doe
                                      email: janedoe567@gmail.com
                                      password: password123
                        example:
                            name: Jane Doe
                            email: janedoe567@gmail.com
                            password: password123
                required: true
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security: []
    /auth/login:
        post:
            tags:
                - Auth
            summary: User Login
            operationId: UserLogin
            parameters: []
            requestBody:
                description: ""
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/UserLoginRequest"
                                - example:
                                      email: janedoe567@gmail.com
                                      password: password123
                        example:
                            email: janedoe567@gmail.com
                            password: password123
                required: true
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security: []
    /jobs:
        post:
            tags:
                - Jobs
            summary: Create job
            operationId: Createjob
            parameters: []
            requestBody:
                description: ""
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/CreatejobRequest"
                                - example:
                                      company: Large company
                                      position: Software Engineer
                        example:
                            company: Large Company
                            position: Software Engineer
                required: true
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        get:
            tags:
                - Jobs
            summary: Get all jobs
            operationId: Getalljobs
            parameters: []
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security:
                - bearer: []
    /jobs/{id}:
        parameters:
            - in: path
              name: id
              schema:
                  type: string
              required: true
              description: The job ID
        patch:
            tags:
                - Jobs
            summary: Update job
            operationId: Updatejob
            parameters: []
            requestBody:
                description: ""
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/UpdatejobRequest"
                                - example:
                                      company: Large company
                                      position: Software Engineer
                        example:
                            company: Large company
                            position: Software Engineer
                required: true
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        get:
            tags:
                - Jobs
            summary: Get job
            operationId: Getjob
            parameters: []
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        delete:
            tags:
                - Jobs
            summary: Delete job
            operationId: Deletejob
            parameters: []
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security:
                - bearer: []
components:
    schemas:
        RegisterUserRequest:
            title: RegisterUserRequest
            required:
                - name
                - email
                - password
            type: object
            properties:
                name:
                    type: string
                email:
                    type: string
                password:
                    type: string
            example:
                name: Name
                email: Email@gmail.com
                password: password123
        UserLoginRequest:
            title: UserLoginRequest
            required:
                - email
                - password
            type: object
            properties:
                email:
                    type: string
                password:
                    type: string
            example:
                email: Email@gmail.com
                password: password123
        CreatejobRequest:
            title: CreatejobRequest
            required:
                - company
                - position
            type: object
            properties:
                company:
                    type: string
                position:
                    type: string
            example:
                company: Large company
                position: Software Engineer
        UpdatejobRequest:
            title: UpdatejobRequest
            required:
                - company
                - position
            type: object
            properties:
                company:
                    type: string
                position:
                    type: string
            example:
                company: Large company
                position: Software Engineer
    securitySchemes:
        bearer:
            type: http
            scheme: bearer
security: []
tags:
    - name: Auth
      description: ""
    - name: Jobs
      description: ""
